[project]
name = "pyedit"
version = "0.0.1"
description = "A simple and minimalist file editor"
authors = [{name = "Matt Kelliher", email = "matthewlkelliher@gmail.com"}]
readme = "README.md"
license = "MIT"
requires-python = ">=3.12"
dependencies = []
